### ISSUE TITLE
Participation & modifications 

### ISSUE THREAD

**Issue by Grise3** [zenith391/numworks-wolfenstein#2]
In English below.

Salutations,

Je souhaiterais participer à ce projet.

Dans le sens, aider à faire des choses, l'améliorer etc.

(Et ça serait cool de changer l'icône =_=)

Comment cela se passerait-il  ?

Cela est-t-il impossible ?

Je comptes également utiliser le moteur actuel, l'améliorer, mettre la version améliorée ici (toujours dans le but d'aider sur ce projet, qui est sympa) et l'utiliser sur mon propre projet, qui St de refaire DooM.

Comment cela se passerait t-il ?

In English.

Hello,

I'd like to participate to this project.

I the way, help to make things, make it better etc.

(Would be nice to change the icon =_=)

Is this possible?

I'd like to make the "engine" better too, put the better version here (in the goal to make this project better, which is nice) and use it on my project, who is to make DooM.

How can I?

**Comment by zenith391** [comment]
Tu peux modifier le projet autant que tu veux en faisant un fork sur GitHub. Aussi le projet est codé en Zig donc faudra connaître ce langage, sinon pour le reste, tu peux me poser des questions par email (que tu peux voir sur mon site) et j'y répondrai peut-être un peu plus rapidement que sur GitHub.
